version: '3.3'
services:
  staging:
    build: .
    image: staging
    container_name: staging
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DOMAIN=${DOMAIN}
      - FRONTEND_URL=${FRONTEND_URL}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - SESSION_SECRET=${SESSION_SECRET}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DATABASE_NAME=${DATABASE_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - postgres
      - redis
    expose:
      - ${PORT}
