name: production

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Docker build and run images
        env:
          PORT: ${{ secrets.PORT }}
          BUILD_TAG: ${{ secrets.BUILD_TAG }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DOMAIN: ${{ secrets.DOMAIN }}
          CERTBOT_EMAIL: ${{ secrets.CERTBOT_EMAIL }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.production.yml build production 
          docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d production
